Add HowLongToBeat feature for discord
the501legion/DiscordBots pull request #32
Opened 2021-09-05 20:00 UTC by Schrotty

Quick and hacky HLTB integration into discord, but fully functional.
Needs testing though, because this version of the bot won't start on my system. Don#t know why.

Usage: !hltb `game`

Result looks like this:
![hltb](https://user-images.githubusercontent.com/5995090/132139873-63fb6dd8-ac3a-4672-a9e1-79f3887b8c74.png)

2021-09-05 20:03 UTC, Schrotty commented
@the501legion @kroonhorstdino @Azidburn *hust* 👀

2021-09-06 14:24 UTC, the501legion requested changes

2021-09-06 14:24 UTC, the501legion commented on PrincessPaperplane/ext/hltb/hltb.py
> +            embeded = Embed(title=g.game_name)
Würde die Variable vielleicht `embedded` oder `embed` nennen 😄

2021-09-06 14:30 UTC, Schrotty commented on PrincessPaperplane/ext/hltb/hltb.py
> +            embeded = Embed(title=g.game_name)
Hups 😄 
Ich push gleich ohnehin noch zwei Kleinigkeiten, dann änder ich das auch noch ^^

2021-09-06 15:20 UTC, Schrotty commented on PrincessPaperplane/ext/hltb/hltb.py
> +            embeded = Embed(title=g.game_name)
Ist gefixt

2021-09-06 15:32 UTC, the501legion approved these changes

2021-09-06 15:32 UTC, merged